CREATE TABLE public."ShiftTransfer" (
    "ShiftTransferId" integer NOT NULL,
    "ShiftId" integer NOT NULL,
    "UserId" integer NOT NULL,
    "TotalReceived" integer NOT NULL,
    "TotalRemaining" integer,
    "LotteryChannelId" integer,
    "LotteryDate" date,
    "ActionBy" integer,
    "ActionByName" character varying(100),
    "ActionDate" timestamp(6) without time zone DEFAULT now(),
    "SalePointid" integer,
    "ShiftDistributeId" integer,
    "LotteryTypeId" integer,
    "TotalTrans" integer,
    "TotalReturns" integer,
    "TotalStocks" integer,
    "TotalSold" integer,
    "TotalSoldMoney" integer,
    "TotalRetail" integer,
    "TotalRetailMoney" integer,
    "TotalWholesale" integer,
    "TotalWholesaleMoney" integer
);